chore(deps-dev): bump prettier from 2.0.5 to 2.1.1
Bumps [prettier](https://github.com/prettier/prettier) from 2.0.5 to 2.1.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/releases">prettier's releases</a>.</em></p>
<blockquote>
<h2>2.1.1</h2>
<p><a href="https://github.com/prettier/prettier/blob/master/CHANGELOG.md#211">🔗Changelog</a></p>
<h1>2.1.0</h1>
<p><a href="https://github.com/prettier/prettier/compare/2.0.5...2.1.0">diff</a></p>
<p>🔗 <a href="https://prettier.io/blog/2020/08/24/2.1.0.html">Release Notes</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/blob/master/CHANGELOG.md">prettier's changelog</a>.</em></p>
<blockquote>
<h1>2.1.1</h1>
<p><a href="https://github.com/prettier/prettier/compare/2.1.0...2.1.1">diff</a></p>
<h4>Fix format on html with frontMatter (<a href="https://github-redirect.dependabot.com/prettier/prettier/pull/9043">#9043</a> by <a href="https://github.com/fisker">@fisker</a>)</h4>
<!-- raw HTML omitted -->
<pre lang="html"><code>&lt;!-- Input --&gt;
---
layout: foo
---
<p>Test &lt;a
href=&quot;<a href="https://prettier.io&amp;quot;&amp;gt;abc&amp;lt;/a">https://prettier.io&amp;quot;&amp;gt;abc&amp;lt;/a</a>&gt;.</p>
<p>&lt;!-- Prettier stable --&gt;
TypeError: Cannot read property 'end' of undefined
...</p>
<h2>&lt;!-- Prettier master --&gt;</h2>
<h2>layout: foo</h2>
<p>Test &lt;a href=&quot;<a href="https://prettier.io&amp;quot;&amp;gt;abc&amp;lt;/a">https://prettier.io&amp;quot;&amp;gt;abc&amp;lt;/a</a>&gt;.
</code></pre></p>
<h4>Fix broken format for <code>...infer T</code> (<a href="https://github-redirect.dependabot.com/prettier/prettier/pull/9044">#9044</a> by <a href="https://github.com/fisker">@fisker</a>)</h4>
<!-- raw HTML omitted -->
<pre lang="typescript"><code>// Input
type Tail&lt;T extends any[]&gt; = T extends [infer U, ...infer R] ? R : never;
<p>// Prettier stable
type Tail&lt;T extends any[]&gt; = T extends [infer U, ...(infer R)] ? R : never;</p>
<p>// Prettier master
type Tail&lt;T extends any[]&gt; = T extends [infer U, ...infer R] ? R : never;
</code></pre></p>
<h4>Fix format on <code>style[lang=&quot;sass&quot;]</code> (<a href="https://github-redirect.dependabot.com/prettier/prettier/pull/9051">#9051</a> by <a href="https://github.com/fisker">@fisker</a>)</h4>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>&lt;!-- Input --&gt;
&lt;style lang=&quot;sass&quot;&gt;
.hero
  @include background-centered
&lt;/tr&gt;&lt;/table&gt; ... (truncated)
</code></pre>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/prettier/prettier/commit/18bcaefc773ba0480aef266350c7af3defcf1f0d"><code>18bcaef</code></a> Release 2.1.1</li>
<li><a href="https://github.com/prettier/prettier/commit/ebe9e07716f0ec1e04efc661bec754321e1c937e"><code>ebe9e07</code></a> Vue: Fix format on self-closing and empty blocks (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/9055">#9055</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/5a12f52bbeccaa1de3e69ab163bd48037e4978c2"><code>5a12f52</code></a> Replace changelog versions in ./scripts/draft-blog-post.js (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/9058">#9058</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/77c8da7691b84e69647dd0ed68a1b64dd8b168fb"><code>77c8da7</code></a> test(TypeScript): test ...infer type with parens (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/9056">#9056</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/ee57066cb49f151843d5a601ab19a9b1bb20df94"><code>ee57066</code></a> HTML: Fix format on <code>style[lang=&quot;sass&quot;]</code> (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/9051">#9051</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/073dfd9fa2c1bb8f93d1e6d2e9b8a30a3d4799c2"><code>073dfd9</code></a> Vue: fix format on blocks with <code>src</code> attribute (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/9052">#9052</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/2a15e273a0a8dc0b389b591ec0d2a0b96593f3d9"><code>2a15e27</code></a> Add <code>loc</code> back for <code>typescript</code> parser (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/9053">#9053</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/720177ac5c04a7860b953fe2c6b51cf725295d77"><code>720177a</code></a> HTML: Fix format on files with frontMatter (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/9043">#9043</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/95504289873b1c6c4597fd45fe8c3a0dedd77973"><code>9550428</code></a> Chore: Update <code>lint:prettier</code> script (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/9045">#9045</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/9a9dcbe12b956afeb5193a44d83cce89f98fe74e"><code>9a9dcbe</code></a> Fix broken format for <code>...infer T</code> (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/9044">#9044</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/prettier/prettier/compare/2.0.5...2.1.1">compare view</a></li>
</ul>
</details>
<details>
<summary>Maintainer changes</summary>
<p>This version was pushed to npm by <a href="https://www.npmjs.com/~sosukesuzuki">sosukesuzuki</a>, a new releaser for prettier since your current version.</p>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=2.0.5&new-version=2.1.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>